sudo: required
language: assembly
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install nasm python moreutils
    - sudo pip install --upgrade pip
    - sudo pip install Image
script:
    - make -C mklvl -f makefile
    - make
after_success:
    - curl -F file="@sokoboot.img" https://filebin.ca/upload.php
    - make clean
