sudo: required
language: assembly
before_install:
    - sudo apt-get update
install:
    - sudo add-apt-repository ppa:jonathonf/python-2.7
    - sudo apt-get update
    - sudo apt-get install 
    - sudo apt-get install nasm python moreutils python2.7
    - python --version  
    - sudo pip install --upgrade pip
    - sudo pip install Image
script:
    - make -C mklvl -f makefile
    - make
after_success:
    - curl -F file="@sokoboot.img" https://filebin.ca/upload.php
    - make clean
